/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Set the directory where the datas (as textures or star catalogs) are
   stored. */
#define CONFIG_DATA_DIR "/usr/local/share/stellarium"

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* If we are on cygwin plateform. */
/*#define CYGWIN 1*/

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define to 1 if translation of program messages to the user's native
   language is requested. */
 #define ENABLE_NLS 1 

/* Define to 1 if you have the `acosf' function. */
/* #undef HAVE_ACOSF */

/* Define to 1 if you have `alloca', as a function or macro. */
/*#define HAVE_ALLOCA 1*/

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
/*#define HAVE_ALLOCA_H 1*/

/* Define to 1 if you have the <argz.h> header file. */
/*#define HAVE_ARGZ_H 1*/

/* Define to 1 if you have the `asinf' function. */
#define HAVE_ASINF 1

/* Define to 1 if you have the `asprintf' function. */
/*#define HAVE_ASPRINTF 1*/

/* Define to 1 if you have the `atan2f' function. */
#define HAVE_ATAN2F 1

/* Define to 1 if you have the `atanf' function. */
#define HAVE_ATANF 1

/* Define to 1 if you have the <byteswap.h> header file. */
/* #undef HAVE_BYTESWAP_H */

/* Define to 1 if you have the `cosf' function. */
#define HAVE_COSF 1

/* Define if the GNU dcgettext() function is already present or preinstalled.
   */
/*#define HAVE_DCGETTEXT 1*/

/* Define to 1 if you have the declaration of `feof_unlocked', and to 0 if you
   don't. */
#define HAVE_DECL_FEOF_UNLOCKED 0

/* Define to 1 if you have the declaration of `fgets_unlocked', and to 0 if
   you don't. */
#define HAVE_DECL_FGETS_UNLOCKED 0

/* Define to 1 if you have the declaration of `getc_unlocked', and to 0 if you
   don't. */
#define HAVE_DECL_GETC_UNLOCKED 0

/* Define to 1 if you have the declaration of `_snprintf', and to 0 if you
   don't. */
#define HAVE_DECL__SNPRINTF 1

/* Define to 1 if you have the declaration of `_snwprintf', and to 0 if you
   don't. */
#define HAVE_DECL__SNWPRINTF 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
/*#define HAVE_DIRENT_H 1*/

/* Define to 1 if you have the `expf' function. */
#define HAVE_EXPF 1

/* Define to 1 if you have the `fwprintf' function. */
#define HAVE_FWPRINTF 1

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the `getegid' function. */
/*#define HAVE_GETEGID 1*/

/* Define to 1 if you have the `geteuid' function. */
/*#define HAVE_GETEUID 1*/

/* Define to 1 if you have the `getgid' function. */
/*#define HAVE_GETGID 1*/

/* Define to 1 if you have the `getpagesize' function. */
/*#define HAVE_GETPAGESIZE 1*/

/* Define if the GNU gettext() function is already present or preinstalled. */
/*#define HAVE_GETTEXT 1*/

/* Define to 1 if you have the `getuid' function. */
/*#define HAVE_GETUID 1*/

/* Define if you have the iconv() function. */
#define HAVE_ICONV 1

/* Define if you have the 'intmax_t' type in <stdint.h> or <inttypes.h>. */
/*#define HAVE_INTMAX_T 1*/

/* Define if <inttypes.h> exists and doesn't clash with <sys/types.h>. */
/*#define HAVE_INTTYPES_H 1*/

/* Define if <inttypes.h> exists, doesn't clash with <sys/types.h>, and
   declares uintmax_t. */
/*#define HAVE_INTTYPES_H_WITH_UINTMAX 1*/

/* Define if you have <langinfo.h> and nl_langinfo(CODESET). */
/*#define HAVE_LANGINFO_CODESET 1*/

/* Define if your <locale.h> file defines LC_MESSAGES. */
/*#define HAVE_LC_MESSAGES 1*/

/* Define to 1 if you have the `freetype' library (-lfreetype). */
/*#define HAVE_LIBFREETYPE 1*/

/* Define to 1 if you have the `GL' library (-lGL). */
/* #undef HAVE_LIBGL */

/* Define to 1 if you have the `GLU' library (-lGLU). */
/* #undef HAVE_LIBGLU */

/* Define to 1 if you have the `MesaGL' library (-lMesaGL). */
/* #undef HAVE_LIBMESAGL */

/* Define to 1 if you have the `MesaGLU' library (-lMesaGLU). */
/* #undef HAVE_LIBMESAGLU */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the `log10f' function. */
#define HAVE_LOG10F 1

/* Define to 1 if you have the `logf' function. */
#define HAVE_LOGF 1

/* Define if you have the 'long double' type. */
#define HAVE_LONG_DOUBLE 1

/* Define if you have the 'long long' type. */
#define HAVE_LONG_LONG 1

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mempcpy' function. */
/*#define HAVE_MEMPCPY 1*/

/* Define to 1 if you have a working `mmap' system call. */
/* #undef HAVE_MMAP */

/* Define to 1 if you have the `modf' function. */
#define HAVE_MODF 1

/* Define to 1 if you have the `munmap' function. */
/*#define HAVE_MUNMAP 1*/

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <nl_types.h> header file. */
/* #undef HAVE_NL_TYPES_H */

/* Define if your printf() function supports format strings with positions. */
/* #undef HAVE_POSIX_PRINTF */

/* Define to 1 if you have the `pow10' function. */
/* #undef HAVE_POW10 */

/* Define to 1 if you have the `powf' function. */
#define HAVE_POWF 1

/* Define to 1 if you have the `putenv' function. */
#define HAVE_PUTENV 1

/* Define to 1 if you have the <SDL_mixer.h> header file. */
/* #undef HAVE_SDL_MIXER_H */

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the `setlocale' function. */
#define HAVE_SETLOCALE 1

/* Define to 1 if you have the `sinf' function. */
#define HAVE_SINF 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the `sqrtf' function. */
#define HAVE_SQRTF 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
/*#define HAVE_STDINT_H 1*/

/* Define if <stdint.h> exists, doesn't clash with <sys/types.h>, and declares
   uintmax_t. */
/*#define HAVE_STDINT_H_WITH_UINTMAX 1*/

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `stpcpy' function. */
/* #undef HAVE_STPCPY */

/* Define to 1 if you have the `strcasecmp' function. */
/*#define HAVE_STRCASECMP 1*/

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the <strings.h> header file. */
/*#define HAVE_STRINGS_H 1*/

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strtoul' function. */
#define HAVE_STRTOUL 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/param.h> header file. */
/*#define HAVE_SYS_PARAM_H 1*/

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `tanf' function. */
#define HAVE_TANF 1

/* Define to 1 if you have the `timegm' function. */
/* #undef HAVE_TIMEGM */

/* Define to 1 if you have the `toupper' function. */
#define HAVE_TOUPPER 1

/* Define to 1 if you have the `tsearch' function. */
/*#define HAVE_TSEARCH 1*/

/* Define to 1 if you have the `tzset' function. */
#define HAVE_TZSET 1

/* Define if you have the 'uintmax_t' type in <stdint.h> or <inttypes.h>. */
/*#define HAVE_UINTMAX_T 1*/

/* Define to 1 if you have the <unistd.h> header file. */
/*#define HAVE_UNISTD_H 1*/

/* Define if you have the 'unsigned long long' type. */
#define HAVE_UNSIGNED_LONG_LONG 1

/* Define if you have the 'wchar_t' type. */
#define HAVE_WCHAR_T 1

/* Define to 1 if you have the `wcslen' function. */
#define HAVE_WCSLEN 1

/* Define if you have the 'wint_t' type. */
#define HAVE_WINT_T 1

/* Define to 1 if you have the `__argz_count' function. */
/*#define HAVE___ARGZ_COUNT 1*/

/* Define to 1 if you have the `__argz_next' function. */
/*#define HAVE___ARGZ_NEXT 1*/

/* Define to 1 if you have the `__argz_stringify' function. */
/*#define HAVE___ARGZ_STRINGIFY 1*/

/* Define to 1 if you have the `__fsetlocking' function. */
/* #undef HAVE___FSETLOCKING */

/* Define as const if the declaration of iconv() needs const. */
/*#define ICONV_CONST const*/

/* Define if integer division by zero raises signal SIGFPE. */
#define INTDIV0_RAISES_SIGFPE 1

/* Set the directory where the locales (translations) are stored. */
#define LOCALEDIR "/usr/local/share/locale"

/* If we are on macosx plateform. */
/* #undef MACOSX */

/* If we are on mingw32 plateform. */
/* #undef MINGW32 */

/* Name of package */
#define PACKAGE "stellarium"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "stellarium@free.fr"

/* Define to the full name of this package. */
#define PACKAGE_NAME "stellarium"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "stellarium argus-cv 0.8.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "stellarium"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.8.2"

/* Define if <inttypes.h> exists and defines unusable PRI* macros. */
/* #undef PRI_MACROS_BROKEN */

/* Define as the maximum value of type 'size_t', if the system doesn't define
   it. */
/* #undef SIZE_MAX */

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.8.2"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to 1 if the X Window System is missing or not being used. */
#define X_DISPLAY_MISSING 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define as the type of the result of subtracting two pointers, if the system
   doesn't define it. */
/* #undef ptrdiff_t */

/* Define to empty if the C compiler doesn't support this keyword. */
/* #undef signed */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to unsigned long or unsigned long long if <stdint.h> and
   <inttypes.h> don't define. */
/* #undef uintmax_t */
