# Collective

collective: stellarium

invitation: false

tiers:
  - tiers: '*'
    labels: ['sponsored']
    message: |-
      Dear <author> :wave:,

      Thank you for this report, and for sponsoring Stellarium via [Open Collective](https://opencollective.com/stellarium).

      We will try to see what we can do, but cannot promise further miracles.






