extraction:
  cpp:
    prepare:
      packages:
      - "qtbase5-dev"
      - "qtscript5-dev"
      - "libqt5svg5-dev"
      - "qttools5-dev"
      - "qttools5-dev-tools"
      - "libqt5opengl5-dev"
      - "qtmultimedia5-dev"
      - "libqt5multimedia5-plugins"
      - "libqt5serialport5"
      - "libqt5serialport5-dev"
      - "qtpositioning5-dev"
      - "libqt5positioning5"
      - "libqt5positioning5-plugins"
      - "qtwebengine5-dev"
      - "libqt5charts5-dev"
      - "zlib1g-dev"
      - "libgps-dev"
      - "libgl1-mesa-dev"
      - "libdrm-dev"
    configure:
      command:
      - wget https://github.com/10110111/CalcMySky/releases/download/v0.1.0/CalcMySky-v0.1.0-linux-amd64-qt5.tar.xz -O CalcMySky.tar.xz
      - tar xvf CalcMySky.tar.xz
      - mv CalcMySky{-*,}
      - mkdir build && cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/src/CalcMySky /opt/src
    index:
      build_command:
        - cd /opt/src/build
        - make
  python:
    python_setup:
      version: 3
