extraction:
  cpp:
    prepare:
      packages:
      - "qtbase5-dev"
      - "qtscript5-dev"
      - "libqt5svg5-dev"
      - "qttools5-dev"
      - "qttools5-dev-tools"
      - "libqt5opengl5-dev"
      - "qtmultimedia5-dev"
      - "libqt5multimedia5-plugins"
      - "libqt5serialport5"
      - "libqt5serialport5-dev"
      - "qtpositioning5-dev"
      - "libqt5positioning5"
      - "libqt5positioning5-plugins"
      - "qtwebengine5-dev"
      - "libqt5charts5-dev"
      - "zlib1g-dev"
      - "libgps-dev"
      - "libgl1-mesa-dev"
      - "libdrm-dev"
  python:
    python_setup:
      version: 3
