# This file used to configure how Typo CI will behave.
---

# What language dictionaries should it use? Currently Typo CI supports:
# de
# en
# en_GB
# es
# fr
# it
# pt
# pt_BR
# tr
dictionaries:
  - en

# Any files/folders we should ignore?
excluded_files:
  - "*.yml"

# Any typos we should ignore?
excluded_words:
  - typoci
  - stellarium

# Would you like filenames to also be spellchecked?
spellcheck_filenames: false
