version: 2
jobs:
  build_stretch:
    docker:
      - image: jochym/indi-stretch
    steps:
      - checkout
      - run: 
          name: Build core
          command: .circleci/build-core.sh
      - run: 
          name: Build libs
          command: .circleci/build-libs.sh
      - run: 
          name: Build 3rd party drivers
          command: .circleci/build-3rdparty.sh
      - run: 
          name: Run tests
          command: .circleci/run-tests.sh

  build_buster:
    docker:
      - image: jochym/indi-buster
    steps:
      - checkout
      - run: 
          name: Build core
          command: .circleci/build-core.sh
      - run: 
          name: Build libs
          command: .circleci/build-libs.sh
      - run: 
          name: Build 3rd party drivers
          command: .circleci/build-3rdparty.sh
      - run: 
          name: Run tests
          command: .circleci/run-tests.sh

  build_artful:
    docker:
      - image: jochym/indi-artful
    steps:
      - checkout
      - run: 
          name: Build core
          command: .circleci/build-core.sh
      - run: 
          name: Build libs
          command: .circleci/build-libs.sh
      - run: 
          name: Build 3rd party drivers
          command: .circleci/build-3rdparty.sh
      - run: 
          name: Run tests
          command: .circleci/run-tests.sh

  build_bionic:
    docker:
      - image: jochym/indi-bionic
    steps:
      - checkout
      - run: 
          name: Build core
          command: .circleci/build-core.sh
      - run: 
          name: Build libs
          command: .circleci/build-libs.sh
      - run: 
          name: Build 3rd party drivers
          command: .circleci/build-3rdparty.sh
      - run: 
          name: Run tests
          command: .circleci/run-tests.sh

  build_clang4:
    docker:
      - image: jochym/indi-artful
        environment:
          CC: clang
          CXX: clang++
    steps:
      - checkout
      - run: 
          name: Build core
          command: .circleci/build-core.sh
      - run: 
          name: Build libs
          command: .circleci/build-libs.sh
      - run: 
          name: Build 3rd party drivers
          command: .circleci/build-3rdparty.sh
      - run: 
          name: Run tests
          command: .circleci/run-tests.sh

  build_clang5:
    docker:
      - image: jochym/indi-bionic
        environment:
          CC: clang
          CXX: clang++
    steps:
      - checkout
      - run: 
          name: Build core
          command: .circleci/build-core.sh
      - run: 
          name: Build libs
          command: .circleci/build-libs.sh
      - run: 
          name: Build 3rd party drivers
          command: .circleci/build-3rdparty.sh
      - run: 
          name: Run tests
          command: .circleci/run-tests.sh

workflows:
  version: 2
  build_all:
    jobs:
      - build_stretch
      - build_buster
      - build_artful
      - build_bionic
      - build_clang4
      - build_clang5
