//
// Name: common objects include file
// License: Public Domain
// Author: Matthew Gates
// Description: Define arrays containing object name (in English).  
//              Defines: planets, constellations, nebulae
//

var planets = new Array("Sun", "Mercury", "Venus", "Moon", "Mars", "Phobos", "Deimos", 
"Jupiter", "Io", "Europa", "Ganymede", "Callisto", "Saturn", "Mimas", "Enceladus", "Tethys", 
"Dione", "Rhea", "Titan", "Hyperion", "Iapetus", "Uranus", "Miranda", "Ariel", "Umbriel", 
"Titania", "Oberon", "Neptune", "Pluto", "Charon", "Solar", "C/2006", "Ceres", "Pallas", "Juno", 
"Vesta", "Eris"); 

var constellations = new Array("Aquila", "Andromeda", "Sculptor", "Ara", "Libra", "Cetus", "Aries",
"Scutum", "Pyxis", "Bootes", "Caelum", "Chamaeleon", "Cancer", "Capricornus", "Carina", "Cassiopeia",
"Centaurus", "Cepheus", "Coma Berenices", "Canes Venatici", "Auriga", "Columba", "Circinus", "Crater",
"Corona Australis", "Corona Borealis", "Corvus", "Crux", "Cygnus", "Delphinus", "Dorado", "Draco",
"Norma", "Eridanus", "Sagitta", "Fornax", "Gemini", "Camelopardalis", "Canis Major", "Ursa Major",
"Grus", "Hercules", "Horologium", "Hydra", "Hydrus", "Indus", "Lacerta", "Monoceros", "Lepus", "Leo",
"Lupus", "Lynx", "Lyra", "Antlia", "Microscopium", "Musca", "Octans", "Apus", "Ophiuchus", "Orion",
"Pavo", "Pegasus", "Pictor", "Perseus", "Equuleus", "Canis Minor", "Leo Minor", "Vulpecula",
"Ursa Minor", "Phoenix", "Pisces", "Piscis Austrinus", "Volans", "Puppis", "Reticulum", "Sagittarius",
"Scorpius", "Scutum", "Serpens", "Sextans", "Mensa", "Taurus", "Telescopium", "Tucana", "Triangulum",
"Triangulum Australe", "Aquarius", "Virgo", "Vela");

var nebulae = new Array("M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "M10", "M11", "M12",
"M13", "M14", "M15", "M16", "M17", "M18", "M19", "M20", "M21", "M22", "M23", "M24", "M25", "M26",
"M27", "M28", "M29", "M30", "M31", "M32", "M33", "M34", "M35", "M36", "M37", "M38", "M39", "M41",
"M42", "M43", "M44", "M46", "M47", "M48", "M49", "M50", "M51", "M51", "M52", "M53", "M54", "M55",
"M56", "M57", "M58", "M59", "M60", "M61", "M62", "M63", "M64", "M65", "M66", "M67", "M68", "M69",
"M70", "M71", "M72", "M73", "M74", "M75", "M76", "M76", "M77", "M78", "M79", "M80", "M81", "M82",
"M83", "M84", "M85", "M86", "M87", "M88", "M89", "M90", "M91", "M92", "M93", "M94", "M95", "M96",
"M97", "M98", "M99", "M100", "M101", "M102", "M103", "M104", "M105", "M106", "M107", "M108",
"M109", "M110", "Horsehead nebula", "California nebula", "Rosette nebula", "NGC253", "NGC6946",
"NGC869", "Pleiades");

