compiler:
 - gcc

language: cpp
sudo: required
dist: trusty
osx_image: xcode8.3

matrix:
  include:
    - os: osx

# Default config (on trusty gcc4)
    - os: linux

    - os: linux
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          packages:
            - g++-7
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - g++-5
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

branches:
  only:
    - master
    - develop
    - package
    - /drv_.*$/
    - travis
    - refactor/unittest
    - feature/travisosx

before_install:
    - eval "${MATRIX_EVAL}"
    - echo Install dependencies
    - travis-ci/deps-${TRAVIS_OS_NAME}.sh

install:
    - echo Building INDI Core and drivers
    - travis-ci/build-core.sh
    - travis-ci/build-libs.sh
    - travis-ci/build-3rdparty.sh
    - travis-ci/build-deb-packages.sh
    - travis-ci/build-core.sh Debug
    - travis-ci/build-libs.sh Debug
    - travis-ci/build-3rdparty.sh Debug
    - travis-ci/build-deb-packages.sh Debug
    - travis-ci/build-core.sh Release
    - travis-ci/build-libs.sh Release
    - travis-ci/build-3rdparty.sh Release
    - travis-ci/build-deb-packages.sh Release

script:
    - travis-ci/run-tests.sh 

