#ifndef _STEL_OBJECT_TYPE_H_
#define _STEL_OBJECT_TYPE_H_

enum STEL_OBJECT_TYPE {
  STEL_OBJECT_UNINITIALIZED,
  STEL_OBJECT_STAR,
  STEL_OBJECT_PLANET,
  STEL_OBJECT_NEBULA,
  STEL_OBJECT_CONSTELLATION,
  STEL_OBJECT_TELESCOPE,
  STEL_OBJECT_VO_OBS
};

#endif
