<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>stellarium</string>
	<key>CFBundleIconFile</key>
	<string>stellarium</string>
	<key>CFBundleIdentifier</key>
	<string>org.stellarium.Stellarium</string>
	<key>CFBundleName</key>
	<string>Stellarium</string>
	<key>CFBundleDisplayName</key>
	<string>Stellarium</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>Stel</string>
	<key>CFBundleVersion</key>
	<string>@VERSION@</string>
	<key>CFBundleShortVersionString</key>
	<string>@VERSION@</string>
	<key>LSMinimumSystemVersion</key>
	<string>@PACKAGE_OSX_TARGET@</string>
	<key>NSHumanReadableCopyright</key>
	<string>@STELLARIUM_COPYRIGHT@</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>NSHighResolutionCapable</key>
	<true/>
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.education</string>
	<key>CFBundleDocumentTypes</key>
	<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Viewer</string>
		<key>CFBundleTypeIconFile</key>
		<string>stellarium.icns</string>
		<key>CFBundleTypeExtensions</key>
		<array>
			<string>ssc</string>
		</array>
		<key>CFBundleTypeMIMETypes</key>
		<array>
			<string>application/x-stellarium-script</string>
		</array>
		<key>CFBundleTypeName</key>
		<string>Stellarium Script</string>
		<key>LSTypeIsPackage</key>
		<false/>
	</dict>
	</array>
</dict>
</plist>
