#
# See https://github.com/marketplace/actions/auto-assign-action
#
name: 'Auto Assign (SC)'
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]
    paths:
      - 'skycultures/**'


jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: "!contains(github.actor, 'transifex')"
    name: Add reviews
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: '.github/auto_assign_sc.yml'
