#
# See https://github.com/marketplace/actions/contextual-qa-checklists
#
name: Contextual QA Checklists

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    if: "!contains(github.actor, 'transifex')"
    name: Checklist job
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Checklist
        uses: wyozi/contextual-qa-checklist-action@dd4b6b51d85a59f537b7ca9e2f162164627ec811 # master
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
