#
# See https://github.com/marketplace/actions/label-commenter
#
name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-latest
    if: "!contains(github.actor, 'transifex')"
    name: Comment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@f0dbbef043eb1b150b566db36b0bdc8b7f505579 # v1.10.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/label-commenter-config.yml
