#
name: "Transifex"

on:
  push:
    branches: [action/transifex]

jobs:
  ci-transifex:
    name: "Check translations"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Transifex client
      run: pip install --user transifex-client

    - name: Prepare and run Transifex client
      run: |
        sudo echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc;
        tx push -s;

